Vagrant.configure("2") do |config|
  config.vm.box = "debian/trixie64"
  config.vm.box_version="13.20260121.1"
  config.vm.provider "libvirt" do |lib|
    lib.cpus = 2
    lib.memory = 1024
    lib.qemu_use_session = false
  end
  config.vm.define "odesseinS" do |control|
    control.vm.hostname = "odesseinS"
    control.vm.network "private_network",  ip: "192.168.56.110"
    control.vm.network "forwarded_port", id: "k3s", guest: 6443, host:6443
    control.vm.provision "shell",
      path: "./scripts/server.sh"
  end
  config.vm.define "odesseinSW" do |control|
    control.vm.hostname = "odesseinSW"
    control.vm.network "private_network",  ip: "192.168.56.111"
    control.vm.provision "shell",
      path: "./scripts/serverWorker.sh"
  end
end
